GetToken: do retry (#230)
We occasionally get something like this:

	ERROR:
	  Code: Unknown
	  Message: SKR failed
	ERROR: Please refer to the documentation for more information on how to use this sidecar.
	...
	: retrieving authentication token failed: pulling http get authentication token response failed: Received invalid token. Please try again.
	: http response status equal to 500 Internal Server Error

"Received invalid token. Please try again." is an error from the ACI managed
identity adapter. It's not clear why this happens but it does seems to be
transient.  Therefore we work around it by doing retry on token fetching.